swagger: 2.0
info:
  title: Apple devices API
  description: Internet Apple Shop API
  version: 1.0.0
servers:
- url: https://h5wzx2j3d5.execute-api.eu-west-1.amazonaws.com/dev/
tags:
- name: Apple devices
  description: Apple devices
paths:
  /products:
    get:
      tags:
      - Products
      summary: Get all devices
      operationId: getProducts
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
  /products/{id}:
    get:
      tags:
      - Product
      summary: Find device by ID
      description: Returns a single device
      operationId: getProduct
      parameters:
      - name: id
        in: path
        description: id of a product to return
        required: true
        schema:
          type: string
          format: uuid
      responses:
        200:
          description: successful operation
          content:
            application/json:
        404:
          description: Product not found
          content: {}
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        count:
          type: integer
        description:
          type: string
        price:
          type: integer
        title:
          type: string
        image:
          type: string
      xml:
        name: Product